stages:
  - plan
  - apply
  - destroy

terraform:
  stage: plan
  script:
    - terraform init \
        -backend-config="address=$TF_BACKEND_ADDRESS" \
        -backend-config="lock_address=$TF_BACKEND_LOCK_ADDRESS" \
        -backend-config="unlock_address=$TF_BACKEND_UNLOCK_ADDRESS" \
        -backend-config="username=$TF_BACKEND_USERNAME" \
        -backend-config="password=$TF_BACKEND_PASSWORD"
    - terraform plan

terraform_apply:
  stage: apply
  script:
    - terraform init \
        -backend-config="address=$TF_BACKEND_ADDRESS" \
        -backend-config="lock_address=$TF_BACKEND_LOCK_ADDRESS" \
        -backend-config="unlock_address=$TF_BACKEND_UNLOCK_ADDRESS" \
        -backend-config="username=$TF_BACKEND_USERNAME" \
        -backend-config="password=$TF_BACKEND_PASSWORD"
    - terraform apply --auto-approve

terraform_destroy:
  stage: destroy
  script:
    - terraform init \
        -backend-config="address=$TF_BACKEND_ADDRESS" \
        -backend-config="lock_address=$TF_BACKEND_LOCK_ADDRESS" \
        -backend-config="unlock_address=$TF_BACKEND_UNLOCK_ADDRESS" \
        -backend-config="username=$TF_BACKEND_USERNAME" \
        -backend-config="password=$TF_BACKEND_PASSWORD"
    - terraform destroy --auto-approve
